### ISSUE TITLE
Error while Reading Data using .readMkT 

### ISSUE THREAD

**Issue by NiciNikolina** [Mircea-MMXXI/azapy#28]
Hi there,

I am trying to optimize a Multi-Asset Portfolio using your azapy library. When trying to load the MktData, as described in your examples like this:

# Collect some market data
mktdir = "../../MkTdata"
sdate = "2012-01-01"
edate = "2021-07-27"
symb = ['GLD', 'TLT', 'XLV', 'IHI', 'PSJ']
mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

Python raises the error: "can't compare offset-naive and offset-aware datetimes". How can I solve this issue?

Thank you very much in advance.
Best
Nicole

**Comment by Mircea-MMXXI** [comment]
Hi Nicole,
I cannot reproduce the error. 
In general, this error message is associated with time zone mismatches in datetime objects!
Do you have more info about the error that you see (like file: line: )?
Best,
Mircea

**Comment by joshwigginton** [comment]
Just tried using this feature also. I get the following error: TypeError: Invalid comparison between dtype=datetime64[ns] and Timestamp

`TypeError                                 Traceback (most recent call last)
File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arrays\datetimelike.py:582, in DatetimeLikeArrayMixin._validate_comparison_value(self, other)
    581 try:
--> 582     self._check_compatible_with(other)
    583 except (TypeError, IncompatibleFrequency) as err:
    584     # e.g. tzawareness mismatch

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:461, in DatetimeArray._check_compatible_with(self, other, setitem)
    460     return
--> 461 self._assert_tzawareness_compat(other)
    462 if setitem:
    463     # Stricter check for setitem vs comparison methods

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:694, in DatetimeArray._assert_tzawareness_compat(self, other)
    693     if other_tz is not None:
--> 694         raise TypeError(
    695             "Cannot compare tz-naive and tz-aware datetime-like objects."
    696         )
    697 elif other_tz is None:

TypeError: Cannot compare tz-naive and tz-aware datetime-like objects.

The above exception was the direct cause of the following exception:

InvalidComparison                         Traceback (most recent call last)
File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arrays\datetimelike.py:1054, in DatetimeLikeArrayMixin._cmp_method(self, other, op)
   1053 try:
-> 1054     other = self._validate_comparison_value(other)
   1055 except InvalidComparison:

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arrays\datetimelike.py:585, in DatetimeLikeArrayMixin._validate_comparison_value(self, other)
    583     except (TypeError, IncompatibleFrequency) as err:
    584         # e.g. tzawareness mismatch
--> 585         raise InvalidComparison(other) from err
    587 elif not is_list_like(other):

InvalidComparison: 2012-01-03 00:00:00-05:00

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[14], line 12
      9 edate = "2021-07-27"
     10 symb = ['GLD', 'TLT', 'XLV', 'IHI', 'PSJ']
---> 12 mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)
     14 #=============================================================================
     15 # Compute portfolio
     16 p4 = az.Port_InvVol(mktdata, pname='InvVolPort')    

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:31, in readMkT(symbol, sdate, edate, calendar, output_format, source, force, save, file_dir, file_format, api_key, param, verbose)
     20 def readMkT(symbol=[], sdate="2012-01-01", edate='today', calendar=None,
     21             output_format='frame', source=None, force=False, save=True,
     22             file_dir="outDir", file_format='csv', api_key=None, param=None,  
     23             verbose=True):
     24     """
     25     Retrive market data for a set of stock symbols.
     26     
   (...)
     29     'MkTreader' member function 'get' (see its doc).
     30     """
---> 31     return MkTreader().get(symbol, sdate, edate, calendar, 
     32                            output_format, source, force, save, 
     33                            file_dir, file_format, api_key, param, 
     34                            verbose)

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:309, in MkTreader.get(self, symbol, sdate, edate, calendar, output_format, source, force, save, file_dir, file_format, api_key, param, verbose)
    307 # output
    308 if verbose:
--> 309     self.get_request_status()
    310     with pd.option_context("display.max_columns", None):
    311         print("\nRequest between "
    312               + f"{self.sdate.date()} : {self.edate.date()}\n"
    313               + f"{self.rout_status}\n"
    314               + f"extraction time {round(self.delta_time, 3)} s")

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:357, in MkTreader.get_request_status(self)
    355     self.rout_status[kk]['sdate'] = sblock.index[0].date()
    356     self.rout_status[kk]['edate'] = sblock.index[-1].date()
--> 357     self._ts_analyzer()
    359 self.rout_status = pd.DataFrame(self.rout_status)
    360 return self.rout_status

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:398, in MkTreader._ts_analyzer(self)
    396 self.rout_status[symbol]['error'] = 'Yes'
    397 self.error_log[symbol] = {}
--> 398 eerr = errdif[errdif < symbData.index[0]]
    399 if not eerr.empty:
    400     self.error_log[symbol]['back'] = eerr

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\ops\common.py:72, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     68             return NotImplemented
     70 other = item_from_zerodim(other)
---> 72 return method(self, other)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arraylike.py:50, in OpsMixin.__lt__(self, other)
     48 @unpack_zerodim_and_defer("__lt__")
     49 def __lt__(self, other):
---> 50     return self._cmp_method(other, operator.lt)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6975, in Index._cmp_method(self, other, op)
   6972         result = op(self._values, other)
   6974 elif isinstance(self._values, ExtensionArray):
-> 6975     result = op(self._values, other)
   6977 elif is_object_dtype(self.dtype) and not isinstance(self, ABCMultiIndex):
   6978     # don't pass MultiIndex
   6979     with np.errstate(all="ignore"):

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\ops\common.py:72, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     68             return NotImplemented
     70 other = item_from_zerodim(other)
---> 72 return method(self, other)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arraylike.py:50, in OpsMixin.__lt__(self, other)
     48 @unpack_zerodim_and_defer("__lt__")
     49 def __lt__(self, other):
---> 50     return self._cmp_method(other, operator.lt)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\arrays\datetimelike.py:1056, in DatetimeLikeArrayMixin._cmp_method(self, other, op)
   1054     other = self._validate_comparison_value(other)
   1055 except InvalidComparison:
-> 1056     return invalid_comparison(self, other, op)
   1058 dtype = getattr(other, "dtype", None)
   1059 if is_object_dtype(dtype):
   1060     # We have to use comp_method_OBJECT_ARRAY instead of numpy
   1061     #  comparison otherwise it would fail to raise when
   1062     #  comparing tz-aware and tz-naive

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\ops\invalid.py:36, in invalid_comparison(left, right, op)
     34 else:
     35     typ = type(right).__name__
---> 36     raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
     37 return res_values

TypeError: Invalid comparison between dtype=datetime64[ns] and Timestamp

​`

**Comment by Mircea-MMXXI** [comment]
Can you send me the script that produces this error?

**Comment by joshwigginton** [comment]
I was trying to use this example from here.  This was the initial error message. It did download the symb data as csv files, but getting this when it attempts to read the GLD

https://azapy.readthedocs.io/en/latest/InvVol_th_doc.html

# Examples
import time
import azapy as az

#=============================================================================
# Collect some market data
mktdir = "../../MkTdata"
sdate = "2012-01-01"
edate = "2021-07-27"
symb = ['GLD', 'TLT', 'XLV', 'IHI', 'PSJ']

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

#=============================================================================
# Compute portfolio
p4 = az.Port_InvVol(mktdata, pname='InvVolPort')    

tic = time.perf_counter()
port4 = p4.set_model()   
toc = time.perf_counter()
print(f"time get_port: {toc-tic}")

ww = p4.get_weights()
p4.port_view()
p4.port_view_all()
p4.port_perf()
p4.port_drawdown(fancy=True)
p4.port_perf(fancy=True)
p4.port_annual_returns()
p4.port_monthly_returns()
p4.port_period_returns()
p4.get_nshares()
p4.get_account(fancy=True)

#=============================================================================
# Test using the Port_Rebalanced weights schedule ww (from above)
p2 = az.Port_Rebalanced(mktdata, pname='TestPort')
port2  = p2.set_model(ww)     
          
# must be identical   
pp = az.Port_Simple([port2, port4])
_ = pp.set_model()
_ = pp.port_view_all(componly=True)



### Error now

read GLD data from file
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File C:\ProgramData\anaconda3\lib\site-packages\pandas\_libs\index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File C:\ProgramData\anaconda3\lib\site-packages\pandas\_libs\index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: Timestamp('2021-07-27 00:00:00')

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6680, in Index.get_slice_bound(self, label, side, kind)
   6679 try:
-> 6680     slc = self.get_loc(label)
   6681 except KeyError as err:

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:3804, in Index.get_loc(self, key, method, tolerance)
   3803 except KeyError as err:
-> 3804     raise KeyError(key) from err
   3805 except TypeError:
   3806     # If we have a listlike key, _check_indexing_error will raise
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.

KeyError: Timestamp('2021-07-27 00:00:00')

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[1], line 12
      9 edate = "2021-07-27"
     10 symb = ['GLD', 'TLT', 'XLV', 'IHI', 'PSJ']
---> 12 mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)
     14 #=============================================================================
     15 # Compute portfolio
     16 p4 = az.Port_InvVol(mktdata, pname='InvVolPort')    

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:31, in readMkT(symbol, sdate, edate, calendar, output_format, source, force, save, file_dir, file_format, api_key, param, verbose)
     20 def readMkT(symbol=[], sdate="2012-01-01", edate='today', calendar=None,
     21             output_format='frame', source=None, force=False, save=True,
     22             file_dir="outDir", file_format='csv', api_key=None, param=None,  
     23             verbose=True):
     24     """
     25     Retrive market data for a set of stock symbols.
     26     
   (...)
     29     'MkTreader' member function 'get' (see its doc).
     30     """
---> 31     return MkTreader().get(symbol, sdate, edate, calendar, 
     32                            output_format, source, force, save, 
     33                            file_dir, file_format, api_key, param, 
     34                            verbose)

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:289, in MkTreader.get(self, symbol, sdate, edate, calendar, output_format, source, force, save, file_dir, file_format, api_key, param, verbose)
    287     xrout = self._alphavantage_process(gr)
    288 elif nm[1] == 'regular':
--> 289     xrout = self._regular_process(gr)
    290 else:
    291     warnings.warn(f"Unknown cathegory {nm}\n {gr}")

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:454, in MkTreader._regular_process(self, data)
    452 for row in data.index:
    453     py = data.loc[row]
--> 454     kod, pri = self._reader_symb(py.symbol, py.source,
    455                                  py.force, py.save, 
    456                                  py.file_dir, py.file_format,
    457                                  py.api_key, py.verbose)
    458     if pri.empty: continue
    459     pri = pri.iloc[[self._bday.is_on_offset(x) for x in pri.index]]

File ~\AppData\Roaming\Python\Python310\site-packages\azapy\MkT\MkTreader.py:518, in MkTreader._reader_symb(self, symbol, source, flag_web_only, flag_save, file_dir, file_format, api_key, verbose)
    515 if verbose:
    516     print(f"read {symbol} data from file")
--> 518 rout = rout_disk.loc[:edate_adj].copy()
    519 rout['adjusted'] = self._adjustDividend(rout)   
    520 sdate_web = rout_disk.index[-1] + self._bday

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexing.py:1073, in _LocationIndexer.__getitem__(self, key)
   1070 axis = self.axis or 0
   1072 maybe_callable = com.apply_if_callable(key, self.obj)
-> 1073 return self._getitem_axis(maybe_callable, axis=axis)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexing.py:1290, in _LocIndexer._getitem_axis(self, key, axis)
   1288 if isinstance(key, slice):
   1289     self._validate_key(key, axis)
-> 1290     return self._get_slice_axis(key, axis=axis)
   1291 elif com.is_bool_indexer(key):
   1292     return self._getbool_axis(key, axis=axis)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexing.py:1324, in _LocIndexer._get_slice_axis(self, slice_obj, axis)
   1321     return obj.copy(deep=False)
   1323 labels = obj._get_axis(axis)
-> 1324 indexer = labels.slice_indexer(slice_obj.start, slice_obj.stop, slice_obj.step)
   1326 if isinstance(indexer, slice):
   1327     return self.obj._slice(indexer, axis=axis)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6559, in Index.slice_indexer(self, start, end, step, kind)
   6516 """
   6517 Compute the slice indexer for input labels and step.
   6518 
   (...)
   6555 slice(1, 3, None)
   6556 """
   6557 self._deprecated_arg(kind, "kind", "slice_indexer")
-> 6559 start_slice, end_slice = self.slice_locs(start, end, step=step)
   6561 # return a slice
   6562 if not is_scalar(start_slice):

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6773, in Index.slice_locs(self, start, end, step, kind)
   6771 end_slice = None
   6772 if end is not None:
-> 6773     end_slice = self.get_slice_bound(end, "right")
   6774 if end_slice is None:
   6775     end_slice = len(self)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6683, in Index.get_slice_bound(self, label, side, kind)
   6681 except KeyError as err:
   6682     try:
-> 6683         return self._searchsorted_monotonic(label, side)
   6684     except ValueError:
   6685         # raise the original KeyError
   6686         raise err

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6629, in Index._searchsorted_monotonic(self, label, side)
   6627 def _searchsorted_monotonic(self, label, side: Literal["left", "right"] = "left"):
   6628     if self.is_monotonic_increasing:
-> 6629         return self.searchsorted(label, side=side)
   6630     elif self.is_monotonic_decreasing:
   6631         # np.searchsorted expects ascending sort order, have to reverse
   6632         # everything for it to work (element ordering, search side and
   6633         # resulting value).
   6634         pos = self[::-1].searchsorted(
   6635             label, side="right" if side == "left" else "left"
   6636         )

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\base.py:1298, in IndexOpsMixin.searchsorted(self, value, side, sorter)
   1294 if not isinstance(values, np.ndarray):
   1295     # Going through EA.searchsorted directly improves performance GH#38083
   1296     return values.searchsorted(value, side=side, sorter=sorter)
-> 1298 return algorithms.searchsorted(
   1299     values,
   1300     value,
   1301     side=side,
   1302     sorter=sorter,
   1303 )

File C:\ProgramData\anaconda3\lib\site-packages\pandas\core\algorithms.py:1669, in searchsorted(arr, value, side, sorter)
   1665     arr = ensure_wrapped_if_datetimelike(arr)
   1667 # Argument 1 to "searchsorted" of "ndarray" has incompatible type
   1668 # "Union[NumpyValueArrayLike, ExtensionArray]"; expected "NumpyValueArrayLike"
-> 1669 return arr.searchsorted(value, side=side, sorter=sorter)

File C:\ProgramData\anaconda3\lib\site-packages\pandas\_libs\tslibs\timestamps.pyx:329, in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__()

**TypeError: can't compare offset-naive and offset-aware datetimes**

**Comment by Mircea-MMXXI** [comment]
Strange - I cannot reproduce it.
However, let's check a few thinks.


mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

In this call the function is trying to read saved data from file ../../MkTdata/GLD.csv . Then, if there is not a such a file or the data in the file is not up to date, it will go to the market data provider (default is yahoo) for/more historical data.

However, in your case, the program stops in the process of reading the GLD.csv file - could it be in a wrong format?!

You can try either:

  1.  clean ../../MkTdata directory (or start with a new clean directory) - then the function will find no files and it will go to the market data provider for historical data.
  2.  add to the function call force=True (to go directly to the market provider without looking for saved data) - ie.  replace the above line with mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir, force=True)

Let me know if this helps.

**Comment by joshwigginton** [comment]
No luck. Cleaned the folder and tried force=True. I am getting the following warning when getting the data

MkTreader.py:498: FutureWarning: Indexing a timezone-aware DatetimeIndex with a timezone-naive datetime is deprecated and will raise KeyError in a future version. Use a timezone-aware object instead.
  rout = rout_web.loc[sdate_adj:edate_adj].copy()

And followed by errors like:
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects.
TypeError: Invalid comparison between dtype=datetime64[ns] and Timestamp

**Comment by Mircea-MMXXI** [comment]
I got it.
I was using an old pandas (1.4.3). This issue comes with 1.5.3.
I will try to do a new release with the fix over the weekend.
I will keep you posted.

Thanks a lot for noticing this.

**Comment by Mircea-MMXXI** [comment]
You may try to upgrade to azapy v 1.1.1 – it is compatible with pandas 1.5.3
Hopefully, this will solve the time-zone problem.

Of course, until the Sumerians will change the pandas time conventions again 😊

Thanks a lot for pointing to this issue.
